name: Build & Test
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      APP_URL: "http://localhost:5173"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: v22.12.0
      - name: Install dependencies
        run: npm ci
      - name: Install Vite (if missing)
        run: npm install vite
      - name: Build
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start dev server
        run: npm run dev & npx wait-on $APP_URL
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
